/* eslint-disable @next/next/no-img-element */
import type { AnchorHTMLAttributes } from "react";

// eslint-disable-next-line jsx-a11y/anchor-has-content
function Link({ href, ...props }: AnchorHTMLAttributes<HTMLAnchorElement> & { href: string }) { return <a href={href} {...props} />; }
import { Footer, Header } from "./site-shell";

const services=[
  {n:"01",title:"Bad",copy:"Vom funktionalen Familienbad bis zur persönlichen Wellnessoase – geplant und umgesetzt aus einer Hand.",href:"/bad",image:"/images/original/WhatsApp-Image-2020-03-25-at-09.05.28-1920w-1920w.jpeg"},
  {n:"02",title:"Heizung",copy:"Moderne Vaillant Heiztechnik, eigener Ersatzteilbestand und verlässlicher Kundendienst über viele Jahre.",href:"/heizung",image:"/images/original/WhatsApp-Image-2020-03-25-at-10.09.18-1920w.jpeg"},
  {n:"03",title:"Gas",copy:"Effiziente Brennwerttechnik und fachgerechter Gas-Check für Komfort und größtmögliche Sicherheit.",href:"/gas",image:"/images/original/10207-7f762aba-960w.jpeg"},
  {n:"04",title:"Solar",copy:"Kostenfreie Sonnenenergie für Warmwasser und solare Heizungsunterstützung – individuell dimensioniert.",href:"/solar",image:"/images/original/125754-1920w.jpeg"},
  {n:"05",title:"Trinkwasser",copy:"Hygiene, zugelassene Materialien und sichere Leitungsdimensionierung gehören in fachkundige Hände.",href:"/wasser",image:"/images/original/114535-98575f63-061d32f4-1920w.jpeg"}
];

export default function Home(){return <><Header/><main>
  <section className="home-hero"><div className="hero-media"><img src="/images/original/WhatsApp-Image-2020-03-25-at-09.05.28-1920w-1920w.jpeg" alt="Modernes Bad von Haustechnik Stachel"/><div className="hero-shade"/></div><div className="hero-layout"><p className="overline">Haustechnik Stachel · Ingolstadt</p><h1>Handwerk für<br/><em>Ihr Zuhause.</em></h1><div className="hero-bottom"><p>Bad, Wärme und Wasser – persönlich geplant, sauber umgesetzt und dauerhaft betreut.</p><Link href="/kontakt" className="round-link" aria-label="Kontakt aufnehmen">↗</Link></div></div><div className="hero-proof"><strong>85+</strong><span>Jahre Erfahrung<br/>im Handwerk</span></div></section>
  <section className="manifest section-pad"><div className="section-index">01</div><div className="manifest-title"><p className="overline">Unser Anspruch</p><h2>Technischer Fortschritt.<br/><em>Handwerkliche Haltung.</em></h2></div><div className="manifest-copy"><p className="large-copy">Ihre Zufriedenheit ist unser Anspruch. Seit über 85 Jahren begleiten wir Menschen in Ingolstadt bei allen Fragen rund um Bad, Heizung, Wasser, Gas, Klima und Solar.</p><p>Unser Schwerpunkt liegt auf Privatkunden, die umfassend bedient und dauerhaft betreut werden möchten. Auch gewerbliche Kunden begleiten wir bei Modernisierungen und Reparaturen.</p><Link href="/unser-team" className="text-arrow">Mehr über uns <span>↗</span></Link></div></section>
  <section className="service-stage"><div className="service-head section-pad"><div><p className="overline">Leistungen</p><h2>Alles aus<br/><em>einer Hand.</em></h2></div><p>Beratung, Planung, Installation, Wartung und Reparatur – klar koordiniert und zuverlässig ausgeführt.</p></div><div className="service-list">{services.map(s=><Link href={s.href} className="service-row" key={s.href}><span className="service-num">{s.n}</span><div className="service-thumb"><img src={s.image} alt=""/></div><h3>{s.title}</h3><p>{s.copy}</p><span className="service-go">↗</span></Link>)}</div></section>
  <section className="motto"><div className="motto-image"><img src="/images/original/IMG_9377-101d9e19-1920w.jpg" alt="Team von Haustechnik Stachel"/></div><div className="motto-copy"><p className="overline">Unser Firmenmotto</p><blockquote>„Kundendienst<br/><em>wird bei uns groß</em><br/>geschrieben.“</blockquote><p>Persönliche Ansprechpartner, qualifizierte Mitarbeiter und ein eigener Ersatzteilbestand sorgen dafür, dass Hilfe nicht nur versprochen wird.</p><Link href="/kontakt" className="text-arrow">Direkt Kontakt aufnehmen <span>↗</span></Link></div></section>
  <section className="projects section-pad"><div className="projects-head"><p className="overline">Ausgewählte Arbeiten</p><h2>Gebaut für den<br/><em>echten Alltag.</em></h2><Link href="/galerie" className="text-arrow">Alle Projekte & Downloads <span>↗</span></Link></div><div className="project-grid"><Link href="/bad" className="project-card project-large"><img src="/images/original/946539dc0000ed5c594f829fec3e755ab67cb3cc907d816490b3de2311995b8b-e6f2b6a7-1920w.jpeg" alt="Komplettsanierung eines Bades"/><div><span>Badrenovierung</span><small>Komplettsanierung & Wellnessdusche</small></div></Link><Link href="/heizung" className="project-card"><img src="/images/original/WhatsApp-Image-2020-03-25-at-10.09.18-1920w.jpeg" alt="Fußbodenheizung"/><div><span>Fußbodenheizung</span><small>Komplette Wohnung</small></div></Link></div></section>
  <section className="backflow-banner"><div className="backflow-photo"><img src="/images/original/R-C3-BCckstauschutz_Kessel-1920w.jpg" alt="Rückstauschutz der Firma Kessel"/></div><div className="backflow-text"><p className="overline">Schutz vor Kanalrückstau</p><h2>Wasser im Keller?<br/><em>Lieber vorbereitet.</em></h2><p>Oft reichen einfache Maßnahmen, um Haus und Eigentum zuverlässig zu schützen. Wir installieren seit vielen Jahren sichere Rückstausicherungen der Firma Kessel aus Lenting.</p><Link href="/aktuelles" className="text-arrow">Mehr zum Rückstauschutz <span>↗</span></Link></div></section>
  <section className="experience-strip"><span>BAD</span><i>·</i><span>HEIZUNG</span><i>·</i><span>WASSER</span><i>·</i><span>GAS</span><i>·</i><span>KLIMA</span><i>·</i><span>SOLAR</span></section>
</main><Footer/></>}
