import Link from "next/link";

const cards = [
  ["Bad", "Planung · Umbau · Wellness", "Individuelle Bäder, sauber geplant und zuverlässig umgesetzt.", "/images/bad.jpg", "/bad"],
  ["Heizung & Sanitär", "Wärme · Wasser · Komfort", "Vaillant Heizungsprodukte, Wartung, Service und Reparatur.", "/images/heizung.jpg", "/heizung"],
  ["Unser Team", "Persönlich · Qualifiziert · Nah", "Erfahrung, die bleibt. Lernen Sie Haustechnik Stachel kennen.", "/images/team.jpg", "/unser-team"],
];

export default function Home() {
  return <main>
    <header className="site-header"><Link href="/" className="brand"><img src="/images/logo.jpg" alt="Haustechnik Stachel" /><span>Haustechnik<br /><b>Stachel</b></span></Link><nav className="desktop-nav"><Link href="/unser-angebot">Für Sie</Link><Link href="/galerie">Unser Angebot</Link><Link href="/unser-team">Über uns</Link><Link href="/ausbildung">Ausbildung</Link></nav><Link href="/kontakt" className="header-call"><span>+49 (841) 95 62 22</span><b>Kontakt ↗</b></Link></header>
    <section className="hero"><div className="hero-image" /><div className="hero-copy"><p className="kicker">Haustechnik aus Ingolstadt · seit über 85 Jahren</p><h1>Wärme, Wasser<br /><em>und Wohlfühlen.</em></h1><p className="hero-text">Wir machen Haustechnik persönlich. Mit Erfahrung, Sorgfalt und dem Anspruch, dass Sie sich jeden Tag auf Ihre Räume verlassen können.</p><div className="hero-actions"><Link className="button button-dark" href="/kontakt">Projekt besprechen <span>↗</span></Link><Link className="text-link" href="/unser-angebot">Leistungen entdecken <span>↗</span></Link></div></div><div className="hero-stamp"><strong>85+</strong><span>Jahre<br />Erfahrung</span></div></section>
    <section className="intro section"><div className="section-label">01 / Das sind wir</div><div className="intro-grid"><h2>Handwerk, das<br /><em>mitdenkt.</em></h2><div><p className="lead">Willkommen bei Haustechnik Stachel. Wir verbinden traditionelles Handwerk mit dem technischen Fortschritt von heute.</p><p>Ihre Zufriedenheit ist unser Anspruch. Wir betreuen Privatkunden umfassend und dauerhaft – und bedienen gewerbliche Kunden bei Modernisierungen und Reparaturen.</p><Link className="arrow-link" href="/unser-team">Lernen Sie uns kennen <span>↗</span></Link></div></div></section>
    <section className="services section"><div className="section-top"><div><div className="section-label">02 / Für Sie</div><h2>Alles aus einer<br /><em>Hand.</em></h2></div><p>Bad, Heizung, Klima, Wasser, Gas, Solar und Abwasser: Service, Kundendienst, Umbau und Modernisierung sind unser Schwerpunkt.</p></div><div className="service-grid">{cards.map(([title, eyebrow, text, image, href], i) => <article className="service-card" key={title}><div className="service-photo" style={{ backgroundImage: `linear-gradient(180deg, transparent 35%, rgba(10,18,20,.72)), url(${image})` }} /><div className="service-content"><div><span className="card-number">0{i + 1}</span><p className="eyebrow">{eyebrow}</p><h3>{title}</h3><p>{text}</p></div><Link href={href}>Mehr erfahren <span>↗</span></Link></div></article>)}</div></section>
    <section className="statement"><div className="statement-inner"><span className="quote-mark">“</span><p>KUNDENDIENST<br /><em>wird bei uns GROSS geschrieben.</em></p><span className="statement-line" /><small>Unser Firmenmotto in einem Satz.</small></div></section>
    <section className="offers section"><div className="section-top"><div><div className="section-label">03 / Unser Angebot</div><h2>Was wir<br /><em>machen.</em></h2></div><p>Von der ersten Idee bis zur sauberen Umsetzung: Wir begleiten Projekte mit Erfahrung, Übersicht und Liebe zum Detail.</p></div><div className="offer-grid"><article className="offer-card"><div className="offer-image" style={{ backgroundImage: "url(/images/angebot-bad.jpg)" }}><span>01</span></div><div className="offer-copy"><h3>Badrenovierung</h3><p>Komplettsanierung von Dusche und Bad und Neueinrichtung einer Wellness-Erlebnis-Dusche.</p><Link href="/galerie" className="arrow-link">Mehr dazu <span>↗</span></Link></div></article><article className="offer-card"><div className="offer-image" style={{ backgroundImage: "url(/images/angebot-heizung.jpg)" }}><span>02</span></div><div className="offer-copy"><h3>Fußbodenheizung</h3><p>Neueinrichtung einer Fußbodenheizung in der kompletten Wohnung.</p><Link href="/galerie" className="arrow-link">Mehr dazu <span>↗</span></Link></div></article></div></section>
    <section className="backflow section"><div className="backflow-image" /><div className="backflow-copy"><div className="section-label">04 / Schutz für Ihr Zuhause</div><h2>Rückstau?<br /><em>Lieber nicht.</em></h2><p className="lead">Hatten Sie noch nie Wasser im Keller?</p><p>Wir bauen seit vielen Jahren die zuverlässigen und sicheren Rückstausicherungen der Firma Kessel aus Lenting ein. Schützen auch Sie sich und Ihr Hab und Gut vor Kanalrückstau.</p><p>In den meisten Fällen helfen einfache Maßnahmen. Nur wer nichts unternimmt, wird durch Schaden klug.</p><Link className="arrow-link" href="/aktuelles">Mehr über Rückstauschutz <span>↗</span></Link></div></section>
    <section className="training section"><div><div className="section-label">05 / Ausbildung</div><h2>Mach was<br /><em>Solides.</em></h2></div><p>Ausbildung ist für uns ein wichtiger Beitrag zur Sicherung des Handwerks – für heute und für unsere Kunden von morgen.</p><Link href="/ausbildung" className="button button-dark">Zur Ausbildung <span>↗</span></Link></section>
    <section className="contact section"><div className="contact-panel"><div><div className="section-label">06 / Kontakt</div><h2>Reden wir<br /><em>über Ihr Projekt.</em></h2><p>Für Bad, Heizung, Wasser, Gas, Klima, Solar, Reparaturen und Vaillant Kundendienst sind wir für Sie da.</p></div><div className="contact-details"><Link href="tel:+49841956222" className="contact-phone">+49 (841) 95 62 22</Link><a href="mailto:info@haustechnik-stachel.de">info@haustechnik-stachel.de</a><p>Frühlingstraße 16<br />85055 Ingolstadt</p></div></div></section>
    <Footer />
  </main>;
}

function Footer() { return <footer><div className="footer-top"><Link href="/" className="brand footer-brand"><img src="/images/logo.jpg" alt="" /><span>Haustechnik<br /><b>Stachel</b></span></Link><p>Seit über 85 Jahren<br />für Sie da.</p><div className="footer-links"><Link href="/unser-angebot">Leistungen</Link><Link href="/galerie">Angebot</Link><Link href="/kontakt">Kontakt</Link><Link href="/notfallnummern">Notfallnummern</Link></div></div><div className="footer-bottom"><span>© Haustechnik Stachel · Inh. Anton Selensky</span><span><Link href="/impressum">Impressum</Link> · <Link href="/datenschutz">Datenschutz</Link></span></div></footer>; }
