export type ContentSection = { heading?: string; paragraphs?: string[]; items?: string[] };
export type SitePage = { title: string; eyebrow: string; intro: string; image?: string; imageAlt?: string; sections: ContentSection[]; related?: string[]; legal?: boolean };

export const routes = ["aktuelles","unser-angebot","bad","heizung","gas","solar","wasser","galerie","unser-team","ausbildung","kontakt","notfallnummern","impressum","datenschutz"];

export const pages: Record<string, SitePage> = {
  aktuelles: { title: "Aktuelles", eyebrow: "Hinweise & Service", intro: "Was Kundinnen und Kunden derzeit wissen sollten.", image: "/images/original/Entw-C3-A4sserungs_Check-1920w.jpg", imageAlt: "Entwässerungs-Check", sections: [
    { heading: "Haben Sie Wasser im Keller gehabt?", paragraphs: ["Wir bauen seit vielen Jahren die zuverlässigen und sicheren Rückstausicherungen der Firma Kessel aus Lenting ein. Schützen auch Sie sich und Ihr Hab und Gut vor Kanalrückstau – auch wenn Sie in den letzten Jahren nicht betroffen waren.", "Viele Betroffene sagten vorher: „Bei uns war so etwas noch nie – und wir wohnen jetzt schon viele Jahre hier.“ In den meisten Fällen helfen einfache Maßnahmen für einen guten Schutz. Wer nichts unternimmt, wird durch Schaden klug."] },
    { heading: "Hinweis zu Infektionslagen", paragraphs: ["Sollte bei Ihnen in der Wohnung oder Hausgemeinschaft eine Person mit ansteckender Erkrankung oder besonderem Schutzbedarf leben, informieren Sie uns bitte bereits bei der telefonischen Terminvereinbarung beziehungsweise vor Betreten der Wohnung."] }
  ], related: ["kontakt","notfallnummern"] },
  "unser-angebot": { title: "Haustechnik für Sie", eyebrow: "Unser Leistungsspektrum", intro: "Ihr Ansprechpartner für Bad, Heizung, Klima, Wasser, Gas, Solar und Abwasser.", image: "/images/original/125754-1920w.jpeg", imageAlt: "Haustechnik in einem Wohnhaus", sections: [
    { heading: "Komplett betreut", paragraphs: ["Service, Kundendienst, Umbau und Modernisierung von Bädern sowie Wasser-, Gas- und Heizungsanlagen bilden den Schwerpunkt unserer Arbeit.", "Wir beraten verständlich, planen bedarfsgerecht und führen die notwendigen Arbeiten sauber und zuverlässig aus."] }
  ], related: ["bad","heizung","gas","solar","wasser"] },
  bad: { title: "Bad", eyebrow: "Planung · Umbau · Wellness", intro: "Ein Bad, das zu Ihren Abläufen, Ihrem Zuhause und Ihrem Stil passt.", image: "/images/original/WhatsApp-Image-2020-03-25-at-09.05.28-1920w-1920w.jpeg", imageAlt: "Modernes von Haustechnik Stachel realisiertes Bad", sections: [
    { heading: "Individuell geplant", paragraphs: ["Wir beraten, planen und helfen bei der Gestaltung Ihres individuellen Bades und führen die notwendigen Arbeiten sauber und zuverlässig aus.", "Durch jahrelange Schulung und Fortbildung sind wir in der Lage, Lösungen genau auf Ihre Bedürfnisse zuzuschneiden und zu Ihrem Vorteil umzusetzen.", "Ihr Auftrag ist für uns eine neue Herausforderung, die bestmögliche Lösung für Ihren Bedarf zu finden – vom funktionalen Bad bis zur persönlichen Wellnessoase und zum Komplettbad aus einer Hand."] }
  ], related: ["unser-angebot","kontakt"] },
  heizung: { title: "Heizung", eyebrow: "Wärme · Wartung · Vaillant", intro: "Effiziente Wärme, qualifizierter Service und ein Ansprechpartner über die gesamte Betriebszeit.", image: "/images/original/WhatsApp-Image-2020-03-25-at-10.09.18-1920w.jpeg", imageAlt: "Moderne Heizungsanlage", sections: [
    { heading: "Technik, die sich einfügt", paragraphs: ["Moderne Heizungsanlagen von Vaillant sind technisch ausgereifte, optisch und akustisch anspruchsvolle Geräte, die sich auf Wunsch perfekt in Ihre Wohnumgebung integrieren.", "Sie erhalten bei uns nicht nur die Heizungsanlage. Wir bleiben über die Betriebsjahre Ihr Ansprechpartner für Wartung, Service und Reparatur."] },
    { heading: "Schnell wieder warm", paragraphs: ["Unsere eigene Ersatzteilhaltung ermöglicht bei einer Störung eine schnelle Verfügbarkeit und damit eine rasche Beseitigung des Problems.", "Jahrzehntelange Erfahrung, die Spezialisierung auf ein Fabrikat, regelmäßige Schulung und der enge Kontakt zum Hersteller sind die Basis unseres qualifizierten Service."] }
  ], related: ["gas","solar","kontakt"] },
  gas: { title: "Gas", eyebrow: "Effizienz · Brennwert · Sicherheit", intro: "Moderne Brennwerttechnik und ein fachgerechter Gas-Check für größtmögliche Sicherheit.", image: "/images/original/10207-7f762aba-960w.jpeg", imageAlt: "Blaue Gasflamme", sections: [
    { heading: "Erdgas", paragraphs: ["Erdgas ist nach wie vor eine saubere Variante für die Beheizung von Wohn- und Gewerbeimmobilien. Energiesparende Brennwerttechnik ist seit Jahren Standard und reduziert den Energieverbrauch gegenüber Altanlagen erheblich.", "Als Betreiber sparen Sie beim Brennstoff und schonen zugleich Ressourcen. Moderne Gas-Heizgeräte von Vaillant machen die im Abgas enthaltene Restwärme nutzbar und erreichen dadurch hohe Effizienz. Gas benötigt keine Lagervorrichtung, spart Platz und ermöglicht flexible Aufstellung."] },
    { heading: "Gas-Check", paragraphs: ["„Gas ganz sicher“ ist die Kampagne der SHK-Branche. Eine genaue Prüfung Ihrer Gasanlage gibt Ihnen Gewissheit, dass die Installation im Haus in Ordnung ist. Werden Mängel entdeckt, ist das der richtige Moment für die erforderlichen Reparaturen.", "Wir beraten Sie gern und entwickeln gemeinsam mit Ihnen eine passende Lösung."] }
  ], related: ["heizung","notfallnummern","kontakt"] },
  solar: { title: "Solar", eyebrow: "Sonnenenergie · Warmwasser · Heizung", intro: "Kostenfreie Energie der Sonne für komfortable und umweltfreundliche Wärme.", image: "/images/original/125754-1920w.jpeg", imageAlt: "Haus mit Solarthermieanlage", sections: [
    { heading: "Wärme zum Nulltarif", paragraphs: ["Thermische Solaranlagen sind heute Standard für viele Neubauten. Ob Aufdach- oder Indachmontage: Sie leisten einen aktiven Beitrag zum Umweltschutz und erzeugen vor Ort umweltfreundliche Wärme für Warmwasser und Heizung.", "Für die Warmwasserbereitung reichen bereits vier bis sechs Quadratmeter Kollektorfläche aus, um ungefähr zwei Drittel der dafür benötigten Energiekosten einzusparen."] },
    { heading: "Maßgeschneidert", paragraphs: ["Die Sonne schickt täglich große Mengen Energie zur Erde – völlig kostenfrei. Mit modernen Solarthermie-Lösungen nutzen Sie diese Kraft für Warmwasser oder solare Heizungsunterstützung.", "Wir beraten Sie und realisieren eine maßgeschneiderte Lösung für hohen Wärmekomfort im Einklang mit der Natur."] }
  ], related: ["heizung","galerie","kontakt"] },
  wasser: { title: "Trinkwasser", eyebrow: "Hygiene · Sicherheit · Fachwissen", intro: "Unser wichtigstes Lebensmittel verdient fachgerechten Schutz.", image: "/images/original/114535-98575f63-061d32f4-1920w.jpeg", imageAlt: "Sauberes Trinkwasser", sections: [
    { heading: "Nichts für Bastler", paragraphs: ["Der Schutz des Trinkwassers und die fachgerechte Verteilung in Gebäuden sind zentrale Aufgaben unseres Handwerks.", "Trinkwasserschutz ist mehr als nur etwas anzuschließen und einzudrehen. Nicht jedes verkaufte Material ist geeignet oder zugelassen.", "Leitungsdimensionierung, erforderliche Schutzeinrichtungen und hygienische Vorsichtsmaßnahmen sind unser Fachgebiet. Wir bieten größtmögliche Sicherheit: Know-how und Markenprodukte statt Improvisation und Billigmaterial."] }
  ], related: ["unser-angebot","kontakt"] },
  galerie: { title: "Projekte & Downloads", eyebrow: "Einblicke in unsere Arbeit", intro: "Realisierte Bäder, Heiztechnik und Solaranlagen – plus Dokumente auf Anfrage.", image: "/images/original/946539dc0000ed5c594f829fec3e755ab67cb3cc907d816490b3de2311995b8b-e6f2b6a7-1920w.jpeg", imageAlt: "Badrenovierung von Haustechnik Stachel", sections: [
    { heading: "Badrenovierung", paragraphs: ["Komplettsanierung von Dusche und Bad sowie Neueinrichtung einer Wellness-Erlebnis-Dusche."] },
    { heading: "Fußbodenheizung", paragraphs: ["Neueinrichtung einer Fußbodenheizung in der kompletten Wohnung."] },
    { heading: "Freistellungsbescheinigungen", paragraphs: ["Bitte fragen Sie die benötigte Freistellungsbescheinigung per E-Mail an info@haustechnik-stachel.de an."] }
  ], related: ["bad","heizung","solar"] },
  "unser-team": { title: "Über uns", eyebrow: "Haustechnik Stachel", intro: "Seit 2024 unter neuer Firmierung – mit vertrauter Erfahrung und unverändert hohem Anspruch.", image: "/images/original/IMG_9377-101d9e19-1920w.jpg", imageAlt: "Das Team von Haustechnik Stachel", sections: [
    { heading: "Vieles bleibt", paragraphs: ["Seit dem 01.01.2024 hat sich bei uns manches verändert, aber das meiste bleibt. Mit der Firmierung Haustechnik Stachel hat sich auch der Inhaber geändert.", "Neuer Firmeninhaber ist Anton Selensky. Als erfahrener Meister war er bereits in den vergangenen Jahren für das operative Geschäft und die Kundenkontakte verantwortlich."] },
    { heading: "Kundendienst wird großgeschrieben", paragraphs: ["Unser Augenmerk liegt vorwiegend auf Privatkunden, die umfassend bedient und dauerhaft betreut werden möchten. Darüber hinaus begleiten wir gewerbliche Kunden bei Modernisierungen und Reparaturen.", "Service, Kundendienst, Umbau und Modernisierung von Bädern sowie Wasser-, Gas- und Heizungsanlagen sind die Schwerpunkte unserer betrieblichen Tätigkeit.", "Obwohl unser Handwerksbetrieb seit über 85 Jahren für Stammkunden tätig ist, haben wir uns kontinuierlich am technischen Fortschritt orientiert und an veränderte Kundenbedürfnisse angepasst."] }
  ], related: ["ausbildung","kontakt"] },
  ausbildung: { title: "Ausbildung", eyebrow: "Handwerk mit Zukunft", intro: "Vielfältig lernen, Verantwortung übernehmen und mit einem sicheren Fundament starten.", image: "/images/original/20190214_154305731_iOS-aaf57bc3-1920w.jpg", imageAlt: "Erfolgreiche Ausbildung im Handwerk", sections: [
    { heading: "Für heute und morgen", paragraphs: ["Ausbildung ist für uns ein wichtiger und notwendiger Beitrag zur Sicherung der handwerklichen Dienstleistung – für heute und für unsere Kunden von morgen.", "Wir legen Wert auf eine umfangreiche, vielfältige Ausbildung. Der erfolgreiche Abschluss bietet einen sicheren Arbeitsplatz und beste Chancen im zukünftigen Berufsleben. Wir freuen uns gemeinsam über jede gelungene Ausbildung."] }
  ], related: ["unser-team","kontakt"] },
  kontakt: { title: "Kontakt", eyebrow: "Direkt zu uns", intro: "Für Heizungswartung und Kundendienst erreichen Sie uns am zuverlässigsten telefonisch.", sections: [
    { heading: "Termin & Kundendienst", paragraphs: ["Derzeit ist keine Onlinekontaktaufnahme für Heizungswartungen und Kundendienst möglich. Wir bitten um Verständnis – Kontaktaufnahme ausschließlich per Telefon unter 0841 95 62 22."] },
    { heading: "Hier finden Sie uns", items: ["Haustechnik Stachel · Inh. Anton Selensky", "Frühlingstraße 16", "85055 Ingolstadt", "Telefon: +49 (841) 95 62 22", "Telefax: +49 (841) 95 62 23", "E-Mail: info@haustechnik-stachel.de"] },
    { heading: "Schließtage 2026", paragraphs: ["Auf der Originalwebsite sind derzeit keine konkreten Schließtage für 2026 veröffentlicht."] }
  ], related: ["notfallnummern"] },
  notfallnummern: { title: "Notfallnummern", eyebrow: "Im Ernstfall", intro: "Die wichtigsten Telefonnummern – schnell erreichbar und klar zugeordnet.", sections: [
    { items: ["Polizei — 110", "Feuerwehr — 112", "Rettungsdienst — 112", "Ärztlicher Notdienst — 116 117", "Stadtwerke · Gasgeruch — +49 (841) 80-0 oder +49 (841) 80-4222", "Vaillant Kundendienst — +49 2191 5767901", "Notdienst Haustechnik Stachel (kostenpflichtig) — +49 841 9512622"] },
    { heading: "Bitte nur für Notfälle", paragraphs: ["Der kostenpflichtige Stachel-Notdienst ist für Gasaustritt, starken Wasseraustritt mit Gefahr für Personen oder Sachwerte sowie Heizungsstörungen bei akuter Frostgefahr vorgesehen – nicht für Komfortfragen wie Warmwasser oder Heizungsstörungen bei gemäßigten Temperaturen."] }
  ], related: ["kontakt"] },
  impressum: { title: "Impressum", eyebrow: "Rechtliche Angaben", intro: "Angaben gemäß den gesetzlichen Informationspflichten.", legal: true, sections: [
    { heading: "Verantwortlich", items: ["Handwerksmeister Anton Selensky", "Frühlingstraße 16", "85055 Ingolstadt", "Telefon: +49 841 956222", "Telefax: +49 841 956223", "E-Mail: info@haustechnik-stachel.de", "Internet: www.stachel-haustechnik.de"] },
    { heading: "Register und Steuer", items: ["Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: DE 323260227", "Inhaltlich Verantwortlicher gemäß § 55 Abs. 2 RStV: Anton Selensky, Frühlingstraße 16, 85055 Ingolstadt"] },
    { heading: "Aufsichtsbehörde und Kammer", items: ["Handwerkskammer München-Oberbayern", "Max-Joseph-Straße 4, 80333 München", "Berufsbezeichnung: Handwerksmeister, verliehen in der Bundesrepublik Deutschland", "Berufsrechtliche Regelung: Handwerksordnung, Bundesgesetzblatt I, Seite 3074 in der Fassung vom 24. September 1998"] },
    { heading: "Haftung für Inhalte", paragraphs: ["Die Inhalte dieser Seiten wurden mit größter Sorgfalt erstellt. Für Richtigkeit, Vollständigkeit und Aktualität können wir jedoch keine Gewähr übernehmen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt."] },
    { heading: "Haftung für Links", paragraphs: ["Unser Angebot kann Links zu externen Webseiten Dritter enthalten, auf deren Inhalte wir keinen Einfluss haben. Für diese fremden Inhalte übernehmen wir keine Gewähr; verantwortlich ist der jeweilige Anbieter. Bei Bekanntwerden von Rechtsverletzungen werden entsprechende Links entfernt."] },
    { heading: "Urheberrecht", paragraphs: ["Die durch den Seitenbetreiber erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung und Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors oder Erstellers."] }
  ] },
  datenschutz: { title: "Datenschutz", eyebrow: "Datenschutzerklärung", intro: "Transparent, sparsam und passend zu diesem Internetauftritt.", legal: true, sections: [
    { heading: "1. Verantwortlicher", items: ["Anton Selensky · Haustechnik Stachel", "Frühlingstraße 16 · 85055 Ingolstadt · Deutschland", "Telefon: +49 841 956222", "Telefax: +49 841 956223", "E-Mail: info@haustechnik-stachel.de", "Datenschutzbeauftragter: Anton Selensky"] },
    { heading: "2. Grundsätze der Verarbeitung", paragraphs: ["Personenbezogene Daten werden nur verarbeitet, soweit dies zur Bereitstellung eines sicheren, funktionsfähigen und nutzerfreundlichen Internetauftritts oder zur Bearbeitung Ihrer Anfrage erforderlich ist. Rechtsgrundlagen sind insbesondere Art. 6 Abs. 1 lit. b und lit. f DSGVO."] },
    { heading: "3. Rechte betroffener Personen", items: ["Auskunft und Kopie der verarbeiteten Daten gemäß Art. 15 DSGVO", "Berichtigung und Vervollständigung gemäß Art. 16 DSGVO", "Löschung oder Einschränkung der Verarbeitung gemäß Art. 17 und 18 DSGVO", "Datenübertragbarkeit gemäß Art. 20 DSGVO", "Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen gemäß Art. 21 DSGVO", "Beschwerde bei einer Datenschutzaufsichtsbehörde gemäß Art. 77 DSGVO"] },
    { heading: "4. Server-Logdaten", paragraphs: ["Beim Aufruf der Website übermittelt Ihr Browser technisch erforderliche Daten an den Hostinganbieter. Dazu können Browsertyp und -version, Betriebssystem, Referrer-URL, aufgerufene Seiten, Datum und Uhrzeit sowie IP-Adresse gehören. Die Verarbeitung dient Sicherheit, Stabilität und Funktionalität der Website auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Die Daten werden gelöscht, sobald sie für diesen Zweck nicht mehr erforderlich sind, soweit keine Aufbewahrung zu Beweiszwecken notwendig ist."] },
    { heading: "5. Kontaktaufnahme", paragraphs: ["Wenn Sie per E-Mail oder Telefon Kontakt aufnehmen, verarbeiten wir Ihre Angaben zur Bearbeitung und Beantwortung der Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Die Daten werden gelöscht, sobald die Anfrage abschließend beantwortet ist und keine gesetzlichen Aufbewahrungspflichten oder eine Vertragsabwicklung entgegenstehen."] },
    { heading: "6. Vertragsabwicklung", paragraphs: ["Daten, die Sie zur Inanspruchnahme unserer Leistungen übermitteln, werden zur Vertragsanbahnung und Vertragsabwicklung verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Steuer- und handelsrechtliche Aufbewahrungsfristen bleiben unberührt."] },
    { heading: "7. Bewerbungen", paragraphs: ["Bewerbungsdaten werden zur Durchführung des Bewerbungsverfahrens auf Grundlage von § 26 Abs. 1 BDSG in Verbindung mit Art. 88 DSGVO verarbeitet. Kommt kein Arbeitsverhältnis zustande, werden die Daten nach Ablauf der zur Rechtsverteidigung erforderlichen Frist gelöscht, sofern keine Einwilligung in eine längere Speicherung vorliegt."] },
    { heading: "8. Cookies, Analyse und externe Medien", paragraphs: ["Diese neu gestaltete Website setzt keine Marketing- oder Analyse-Cookies, keine Social-Media-Plug-ins und keine eingebetteten Karten oder Videos ein. Es findet daher über diese Website keine entsprechende Übermittlung an Google, Meta, X oder andere Werbeplattformen statt. Externe Seiten werden erst aufgerufen, wenn Sie einen entsprechend gekennzeichneten Link anklicken."] },
    { heading: "9. Speicherdauer und Aktualität", paragraphs: ["Daten werden gelöscht oder gesperrt, sobald der Zweck der Speicherung entfällt und keine gesetzlichen Aufbewahrungspflichten entgegenstehen. Wir passen diese Datenschutzerklärung an, wenn sich Funktionen oder rechtliche Anforderungen ändern."] }
  ] }
};

export const labels: Record<string,string> = { aktuelles:"Aktuelles","unser-angebot":"Leistungen",bad:"Bad",heizung:"Heizung",gas:"Gas",solar:"Solar",wasser:"Trinkwasser",galerie:"Projekte & Downloads","unser-team":"Über uns",ausbildung:"Ausbildung",kontakt:"Kontakt",notfallnummern:"Notfallnummern",impressum:"Impressum",datenschutz:"Datenschutz" };
