"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { useEffect, useState } from "react";

const serviceLinks = [["Bad","/bad"],["Heizung","/heizung"],["Gas","/gas"],["Solar","/solar"],["Trinkwasser","/wasser"]];

export function Header() {
  const [open,setOpen]=useState(false);
  useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);
  return <header className="site-header"><Link href="/" className="brand" onClick={()=>setOpen(false)}><img src="/images/original/LOGO_H-1-1920w.JPG" alt="Haustechnik Stachel"/><span><b>STACHEL</b><small>HAUSTECHNIK · INGOLSTADT</small></span></Link><nav className="desktop-nav"><div className="nav-group"><Link href="/unser-angebot">Leistungen</Link><div className="nav-dropdown">{serviceLinks.map(([l,h])=><Link href={h} key={h}>{l}<span>↗</span></Link>)}</div></div><Link href="/galerie">Projekte</Link><Link href="/unser-team">Unternehmen</Link><Link href="/ausbildung">Ausbildung</Link><Link href="/aktuelles">Aktuelles</Link></nav><div className="header-actions"><a className="phone-mini" href="tel:+49841956222">0841 95 62 22</a><Link href="/kontakt" className="header-cta">Anfragen <span>↗</span></Link><button className="menu-toggle" aria-label={open?"Menü schließen":"Menü öffnen"} aria-expanded={open} onClick={()=>setOpen(!open)}><i/><i/></button></div><div className={`mobile-nav ${open?"is-open":""}`}><div className="mobile-nav-main"><Link href="/" onClick={()=>setOpen(false)}>Startseite</Link><Link href="/unser-angebot" onClick={()=>setOpen(false)}>Leistungen</Link>{serviceLinks.map(([l,h])=><Link className="sub" href={h} key={h} onClick={()=>setOpen(false)}>{l}</Link>)}<Link href="/galerie" onClick={()=>setOpen(false)}>Projekte & Downloads</Link><Link href="/unser-team" onClick={()=>setOpen(false)}>Über uns</Link><Link href="/ausbildung" onClick={()=>setOpen(false)}>Ausbildung</Link><Link href="/aktuelles" onClick={()=>setOpen(false)}>Aktuelles</Link></div><div className="mobile-nav-meta"><a href="tel:+49841956222">+49 (841) 95 62 22</a><a href="mailto:info@haustechnik-stachel.de">info@haustechnik-stachel.de</a><span>Frühlingstraße 16 · 85055 Ingolstadt</span></div></div></header>;
}

export function Footer() { return <footer className="site-footer"><div className="footer-cta"><p>Ihr Projekt beginnt mit<br/><em>einem guten Gespräch.</em></p><Link href="/kontakt">Kontakt aufnehmen <span>↗</span></Link></div><div className="footer-grid"><div className="footer-brand"><img src="/images/original/LOGO_H-1-1920w.JPG" alt=""/><p>Haustechnik Stachel<br/><span>Inh. Anton Selensky</span></p></div><div><strong>Leistungen</strong><Link href="/bad">Bad</Link><Link href="/heizung">Heizung</Link><Link href="/gas">Gas</Link><Link href="/solar">Solar</Link><Link href="/wasser">Trinkwasser</Link></div><div><strong>Unternehmen</strong><Link href="/unser-team">Über uns</Link><Link href="/ausbildung">Ausbildung</Link><Link href="/aktuelles">Aktuelles</Link><Link href="/galerie">Projekte & Downloads</Link></div><div><strong>Kontakt</strong><a href="tel:+49841956222">+49 (841) 95 62 22</a><a href="mailto:info@haustechnik-stachel.de">info@haustechnik-stachel.de</a><span>Frühlingstraße 16<br/>85055 Ingolstadt</span></div></div><div className="footer-base"><span>© {new Date().getFullYear()} Haustechnik Stachel</span><div><Link href="/notfallnummern">Notfallnummern</Link><Link href="/impressum">Impressum</Link><Link href="/datenschutz">Datenschutz</Link></div></div></footer> }
