import Link from "next/link";

const pages: Record<string, { title: string; intro?: string; body: string[]; image?: string; links?: [string, string][] }> = {
  "unser-angebot": { title: "Haustechnik für Sie", intro: "Ihr Ansprechpartner für Bad · Heizung · Klima · Wasser · Gas · Solar · Abwasser", body: ["Wir verbinden Beratung, Planung und saubere Ausführung mit einem persönlichen Kundendienst.", "Für Bad, Heizung, Wasser, Gas, Klima, Solar, Reparaturen und Vaillant Kundendienst sind wir für Sie da."], links: [["Bad", "/bad"], ["Heizung", "/heizung"], ["Gas", "/gas"], ["Solar", "/solar"], ["Trinkwasser", "/wasser"]] },
  bad: { title: "Bad", intro: "Ihr Bad. Ihre Bedürfnisse. Unsere Erfahrung.", body: ["Wir beraten, planen und helfen bei der Gestaltung Ihres individuellen Bades und führen die notwendigen Arbeiten sauber und zuverlässig aus.", "Durch jahrelange Schulung und Fortbildung sind wir in der Lage, Lösungen, die genau auf Ihre Bedürfnisse zugeschnitten sind, zu Ihrem Vorteil umzusetzen. Ihr Auftrag ist für uns eine neue Herausforderung, die bestmögliche Lösung für Ihren Bedarf zu finden."], image: "/images/bad.jpg" },
  heizung: { title: "Heizung", intro: "Wärme, die zuverlässig bleibt.", body: ["Moderne Heizungsanlagen von Vaillant sind technisch ausgereifte, optisch und akustisch anspruchsvolle Geräte, die sich perfekt in Ihre Wohnumgebung integrieren.", "Sie erhalten bei uns nicht nur die Heizungsanlage, sondern wir sind auch über die Betriebsjahre Ihr Ansprechpartner für Wartung, Service und Reparatur.", "Unsere eigene Ersatzteilhaltung bietet im Falle einer Störung schnellstmögliche Verfügbarkeit. Jahrzehntelange Erfahrung, Schulung und enger Kontakt zum Hersteller sind die Basis für qualifizierten Service."], image: "/images/heizung.jpg" },
  gas: { title: "Gas", intro: "Sicher planen. Sauber ausführen.", body: ["Gasinstallationen gehören in erfahrene Hände. Wir beraten, modernisieren und reparieren Gas- und Heizungsanlagen zuverlässig und mit dem Blick für Sicherheit und Langlebigkeit."], image: "/images/heizung.jpg" },
  solar: { title: "Solar", intro: "Wärme von der Sonne – direkt bei Ihnen.", body: ["Thermische Solaranlagen sind heute Standard für viele Neubauten. Ob Aufdach- oder Indachmontage: Solaranlagen sind ein aktiver Beitrag zum Umweltschutz und erzeugen umweltfreundlich Wärme für Warmwasser und Heizung.", "Flachkollektoren bieten Wärme zum Null-Tarif. Zur Erzeugung von Warmwasser reichen bereits 4–6 m² Kollektorfläche aus, um etwa zwei Drittel der Energiekosten für die Warmwasserbereitung einzusparen.", "Wir beraten Sie gern und realisieren Ihre maßgeschneiderte Lösung für höchsten Wärmekomfort im Einklang mit der Natur."], image: "/images/angebot-heizung.jpg" },
  wasser: { title: "Trinkwasser", intro: "Unser wichtigstes Lebensmittel.", body: ["Der Schutz des Trinkwassers und die fachgerechte Verteilung in Gebäuden ist eine unserer zentralen Aufgaben. Das ist nichts für Bastler.", "Trinkwasserschutz ist mehr als nur irgendwas anschließen und eindrehen. Leitungsdimensionierung, Schutzeinrichtungen und hygienische Vorsichtsmaßnahmen sind unser Fachgebiet.", "Wir bieten größtmögliche Sicherheit – Know-how und Markenprodukte statt Basteln und Billigramsch."], image: "/images/rueckstauschutz.jpg" },
  galerie: { title: "Downloads & Projekte", intro: "Freistellungsbescheinigungen und ausgewählte Arbeiten.", body: ["Freistellungsbescheinigungen bitte per Mail anfragen. Weitere Informationen und Projektbeispiele erhalten Sie direkt von uns."], image: "/images/angebot-bad.jpg" },
  "unser-team": { title: "Über uns", intro: "Seit 01.01.2024 hat sich bei uns manches verändert, aber das meiste bleibt.", body: ["Mit der neuen Firmierung Haustechnik Stachel hat sich auch der Inhaber geändert. Neuer Firmeninhaber ist Herr Anton Selensky, der schon in den letzten Jahren für das operative Geschäft und die Kundenkontakte als erfahrener Meister verantwortlich war.", "KUNDENDIENST wird bei uns GROSS geschrieben. Vorwiegendes Augenmerk haben wir auf Privatkunden gerichtet, die umfassend bedient und dauerhaft betreut werden möchten. Darüber hinaus bedienen wir gewerbliche Kunden bei Modernisierungen und Reparaturen.", "Obwohl unser Handwerksbetrieb schon über 85 Jahre für Stammkunden tätig ist, haben wir uns kontinuierlich am technischen Fortschritt orientiert."], image: "/images/team.jpg" },
  ausbildung: { title: "Ausbildung", intro: "Ein Beruf mit Zukunft. Ein Handwerk mit Sinn.", body: ["Ausbildung ist für uns ein ganz wichtiger und notwendiger Beitrag zur Sicherung der handwerklichen Dienstleistung – für heute und für unsere Kunden von morgen.", "Wir legen Wert auf eine umfangreiche, vielfältige Ausbildung. Der erfolgreiche Abschluss bietet einen sicheren Arbeitsplatz und beste Chancen im zukünftigen Berufsleben. Wir freuen uns gemeinsam über jede gelungene Ausbildung."], image: "/images/team.jpg" },
  aktuelles: { title: "Aktuelles", intro: "Wichtige Informationen und Hinweise.", body: ["Corona hat auch uns im Griff! Derzeit ist eine zuverlässige Planung schwierig, Liefertermine sind teilweise nicht haltbar, Mitarbeiter wegen der aktuellen Gefährdungslage nur beschränkt einsetzbar. Wir bitten um Ihr Verständnis.", "Sollte bei Ihnen eine Person mit Corona-Verdacht, nachgewiesener Infektion, eine Risikoperson oder eine Person aus einem Risikogebiet leben, bitten wir um unaufgeforderte Information unserer Mitarbeiter bereits bei der telefonischen Terminvereinbarung bzw. vor Betreten der Wohnung.", "Haben Sie auch Wasser im Keller gehabt? Wir bauen seit vielen Jahren zuverlässige und sichere Rückstausicherungen der Firma Kessel aus Lenting ein."], image: "/images/rueckstauschutz.jpg" },
  kontakt: { title: "Ihr Kontakt zu uns", intro: "Anfragen für Heizungswartungen und Kundendienst", body: ["Derzeit ist keine Onlinekontaktaufnahme möglich. Wir bitten um Verständnis – Kontaktaufnahme nur per Telefon: 0841-95 62 22.", "Hier finden Sie uns in Ingolstadt: Frühlingstraße 16, 85055 Ingolstadt.", "Für Bad, Heizung, Wasser, Gas, Klima, Solar, Reparaturen und Vaillant Kundendienst sind wir für Sie da."] },
  notfallnummern: { title: "Notfallnummern", intro: "Bitte nur für echte Notfälle.", body: ["Polizei: 110", "Feuerwehr: 112", "Rettungsdienst: 112", "Ärztlicher Notdienst: 116 117", "Stadtwerke – Gasgeruch: +49 (841) 80-0 · +49 (841) 80-4222", "Vaillant Kundendienst: +49 2191-5767901", "Notdienst (kostenpflichtig) Fa. Stachel: +49 841 / 9512622", "Bitte nur bei Gasaustritt, starkem Wasseraustritt mit Gefahr für Personen und Sachwerte oder akuter Frostgefahr anrufen – nicht für Komfortfragen."] },
  impressum: { title: "Impressum", intro: "Verantwortlich", body: ["Handwerksmeister Anton Selensky", "Frühlingstr. 16 · 85055 Ingolstadt", "Telefon: +49 841 956222", "E-Mail: info@haustechnik-stachel.de", "Internet: www.stachel-haustechnik.de", "Umsatzsteuer-ID: DE 323260227", "Aufsichtsbehörde und zuständige Kammer: Handwerkskammer München-Oberbayern, Max-Joseph-Straße 4, 80333 München", "Berufsbezeichnung: Handwerksmeister (verliehen in der Bundesrepublik Deutschland)", "Berufsrechtliche Regelungen: Handwerksordnung"] },
  datenschutz: { title: "Datenschutz", intro: "Informationen zum Schutz Ihrer Daten.", body: ["Wir nehmen den Schutz Ihrer persönlichen Daten ernst. Personenbezogene Daten werden nur im Rahmen der gesetzlichen Bestimmungen verarbeitet.", "Wenn Sie uns telefonisch oder per E-Mail kontaktieren, verwenden wir Ihre Angaben ausschließlich zur Bearbeitung Ihrer Anfrage und zur Kommunikation mit Ihnen.", "Für vollständige Auskünfte zu Ihren Rechten und zur Datenverarbeitung wenden Sie sich bitte an info@haustechnik-stachel.de."] },
};

export default async function DetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = pages[slug] ?? pages["unser-angebot"];
  return <main className="detail-page"><header className="site-header"><Link href="/" className="brand"><img src="/images/logo.jpg" alt="Haustechnik Stachel" /><span>Haustechnik<br /><b>Stachel</b></span></Link><nav className="desktop-nav"><Link href="/unser-angebot">Für Sie</Link><Link href="/galerie">Unser Angebot</Link><Link href="/unser-team">Über uns</Link><Link href="/ausbildung">Ausbildung</Link></nav><Link href="/kontakt" className="header-call"><span>+49 (841) 95 62 22</span><b>Kontakt ↗</b></Link></header><section className="detail-hero"><div className="detail-hero-copy"><Link href="/" className="back-link">← Startseite</Link><p className="kicker">Haustechnik Stachel · Ingolstadt</p><h1>{page.title}</h1>{page.intro && <p className="detail-intro">{page.intro}</p>}</div>{page.image && <div className="detail-hero-image" style={{ backgroundImage: `url(${page.image})` }} />}</section><section className="detail-content"><div className="detail-main">{page.body.map((paragraph, i) => <p key={i} className={i === 0 ? "detail-lead" : ""}>{paragraph}</p>)}{page.links && <div className="detail-links">{page.links.map(([label, href]) => <Link key={href} href={href}>{label}<span>↗</span></Link>)}</div>}</div><aside><span className="section-label">Service</span><h2>Seit über<br /><em>85 Jahren.</em></h2><p>Für Bad, Heizung, Wasser, Gas, Klima, Solar, Reparaturen und Vaillant Kundendienst sind wir für Sie da.</p><Link className="button button-dark" href="/kontakt">Kontakt aufnehmen <span>↗</span></Link></aside></section><footer><div className="footer-bottom"><span>© Haustechnik Stachel · Inh. Anton Selensky</span><span><Link href="/impressum">Impressum</Link> · <Link href="/datenschutz">Datenschutz</Link> · <Link href="/notfallnummern">Notfallnummern</Link></span></div></footer></main>;
}
